#############################################################################
# Deprovision Memcahed cluster
#############################################################################

- name: Remove ElastiCache Memcached cluster
  cloudformation:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    stack_name: "apb-memcached-{{ stack_identifier }}"
    state: "absent"
    region: "{{ region }}"
