AWSTemplateFormatVersion: 2010-09-09
Description: ' ElastiCache Template for Production memcached'
Parameters:
  ApplicationName:
    Description: >-
      This will be set as the value for the "APPLICATION_NAME" tag on all
      supported resources
    Type: String
  VpcId:
    Description: The ID of the VPC to launch the Memcache cluster into
    Type: 'AWS::EC2::VPC::Id'
  NumberOfAvailabilityZones:
    Description: >-
      Quantity of subnets to use, if selecting more than 2 the region this stack
      is in must have at least that many Availability Zones
    Type: String
    Default: '3'
    AllowedValues:
      - '2'
      - '3'
      - '4'
      - '5'
  PreferredMaintenanceWindowDay:
    Description: The day of the week which ElastiCache maintenance will be performed
    Type: String
    Default: Mon
    AllowedValues:
      - Mon
      - Tue
      - Wed
      - Thu
      - Fri
      - Sat
      - Sun
  PreferredMaintenanceWindowStartTime:
    Description: >-
      The weekly start time in UTC for the ElastiCache maintenance window, must
      be less than PreferredMaintenanceWindowEndTime and cannot overlap with
      PreferredBackupWindow
    Type: String
    Default: '04:00'
    AllowedValues:
      - '00:00'
      - '01:00'
      - '02:00'
      - '03:00'
      - '04:00'
      - '05:00'
      - '06:00'
      - '07:00'
      - '08:00'
      - '09:00'
      - '10:00'
      - '11:00'
      - '12:00'
      - '13:00'
      - '14:00'
      - '15:00'
      - '16:00'
      - '17:00'
      - '18:00'
      - '19:00'
      - '20:00'
      - '21:00'
      - '22:00'
  PreferredMaintenanceWindowEndTime:
    Description: >-
      The weekly end time in UTC for the ElastiCache maintenance window, must be
      more than PreferredMaintenanceWindowEndTime and cannot overlap with
      PreferredBackupWindow
    Type: String
    Default: '06:00'
    AllowedValues:
      - '00:00'
      - '01:00'
      - '02:00'
      - '03:00'
      - '04:00'
      - '05:00'
      - '06:00'
      - '07:00'
      - '08:00'
      - '09:00'
      - '10:00'
      - '11:00'
      - '12:00'
      - '13:00'
      - '14:00'
      - '15:00'
      - '16:00'
      - '17:00'
      - '18:00'
      - '19:00'
      - '20:00'
      - '21:00'
      - '22:00'
  AvailabilityZones:
    Description: >-
      list of availability zones to use, must be the same quantity as specified
      in NumberOfAvailabilityZones
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  CidrBlocks:
    Description: >-
      comma seperated list of CIDR blocks to place ElastiCache into, must be the
      same quantity as specified in NumberOfAvailabilityZones
    Type: CommaDelimitedList
    Default: '172.31.129.0/25,172.31.129.128/25,172.31.130.0/25'
  AccessCidr:
    Description: CIDR block to allow to connect to database
    Type: String
  CacheNodeType:
    Description: The compute and memory capacity of nodes in a cache cluster.
    Type: String
    AllowedValues:
      - cache.t2.small
      - cache.t2.medium
      - cache.m3.medium
      - cache.m3.large
      - cache.m3.xlarge
      - cache.m3.2xlarge
      - cache.m4.medium
      - cache.m4.large
      - cache.m4.xlarge
      - cache.m4.2xlarge
      - cache.m4.4xlarge
      - cache.m4.10xlarge
      - cache.r4.large
      - cache.r4.xlarge
      - cache.r4.2xlarge
      - cache.r4.4xlarge
      - cache.r4.8xlarge
    Default: cache.m4.large
  EngineVersion:
    Description: Family to be used with cluster or parameter group
    Type: String
    AllowedValues:
      - 1.4.34
      - 1.4.33
      - 1.4.24
      - 1.4.5
    Default: 1.4.34
  NumCacheNodes:
    Description: The number of cache nodes in the cluster.
    Type: String
    Default: '3'
  ClusterType:
    Description: >-
      The type of cluster. Specify single-node or multi-node (default).  Number
      of nodes must be greater than 1 for multi-node
    Type: String
    AllowedValues:
      - single-node
      - multi-node
    Default: multi-node
  AllowVersionUpgrade:
    Description: >-
      Indicates that minor engine upgrades will be applied automatically to the
      cache cluster during the maintenance window. The default value is true. 
    Type: String
    Default: 'True'
    AllowedValues:
      - 'True'
      - 'False'
  PortNumber:
    Description: The port number for the Cluster to listen on
    Type: Number
    Default: '5439'
    MinValue: '1150'
    MaxValue: '65535'
  AZMode:
    Description: >-
      Specifies whether the nodes in this Memcached cluster are created in a
      single Availability Zone or created across multiple Availability Zones in
      the cluster's region. This parameter is only supported for Memcached cache
      clusters. If the AZMode and PreferredAvailabilityZones are not specified,
      ElastiCache assumes single-az mode. 
    Type: String
    Default: cross-az
    AllowedValues:
      - single-az
      - cross-az
Conditions:
  3az: !Or 
    - !Equals 
      - !Ref NumberOfAvailabilityZones
      - '3'
    - !Equals 
      - !Ref NumberOfAvailabilityZones
      - '4'
    - !Equals 
      - !Ref NumberOfAvailabilityZones
      - '5'
  4az: !Or 
    - !Equals 
      - !Ref NumberOfAvailabilityZones
      - '4'
    - !Equals 
      - !Ref NumberOfAvailabilityZones
      - '5'
  5az: !Equals 
    - !Ref NumberOfAvailabilityZones
    - '5'
  Cross-AZ: !Equals 
    - !Ref AZMode
    - cross-az
Resources:
  ElastiCacheCluster:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      AutoMinorVersionUpgrade: !Ref AllowVersionUpgrade
      AZMode: !Ref AZMode
      CacheNodeType: !Ref CacheNodeType
      CacheParameterGroupName: !Ref ElasticacheParameterGroup
      CacheSubnetGroupName: !Ref ClusterSubnetGroup
      Engine: memcached
      EngineVersion: !Ref EngineVersion
      NumCacheNodes: !Ref NumCacheNodes
      Port: !Ref PortNumber
      PreferredAvailabilityZones: !Ref AvailabilityZones
      PreferredMaintenanceWindow: !Sub >-
        ${PreferredMaintenanceWindowDay}:${PreferredMaintenanceWindowStartTime}-${PreferredMaintenanceWindowDay}:${PreferredMaintenanceWindowEndTime}
      Tags:
        - Key: ApplicationName
          Value: !Ref ApplicationName
      VpcSecurityGroupIds:
        - !Ref ClusterSecurityGroup
  ElasticacheParameterGroup:
    Type: 'AWS::ElastiCache::ParameterGroup'
    Properties:
      CacheParameterGroupFamily: memcached1.4
      Description: !Sub 'Application: ${ApplicationName}'
      Properties: {}
  ClusterSubnetGroup:
    Type: 'AWS::ElastiCache::SubnetGroup'
    Properties:
      Description: !Sub 'Application: ${ApplicationName}'
      SubnetIds:
        - !Ref ClusterSubnet1
        - !Ref ClusterSubnet2
        - !If 
          - 3az
          - !Ref ClusterSubnet3
          - !Ref 'AWS::NoValue'
        - !If 
          - 4az
          - !Ref ClusterSubnet4
          - !Ref 'AWS::NoValue'
        - !If 
          - 5az
          - !Ref ClusterSubnet5
          - !Ref 'AWS::NoValue'
  ClusterSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !Ref AvailabilityZones
      VpcId: !Ref VpcId
      CidrBlock: !Select 
        - 0
        - !Ref CidrBlocks
      Tags:
        - Key: APPLICATION_NAME
          Value: !Ref ApplicationName
  ClusterSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select 
        - 1
        - !Ref AvailabilityZones
      VpcId: !Ref VpcId
      CidrBlock: !Select 
        - 1
        - !Ref CidrBlocks
      Tags:
        - Key: APPLICATION_NAME
          Value: !Ref ApplicationName
  ClusterSubnet3:
    Condition: 3az
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select 
        - 2
        - !Ref AvailabilityZones
      VpcId: !Ref VpcId
      CidrBlock: !Select 
        - 2
        - !Ref CidrBlocks
      Tags:
        - Key: APPLICATION_NAME
          Value: !Ref ApplicationName
  ClusterSubnet4:
    Condition: 4az
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select 
        - 3
        - !Ref AvailabilityZones
      VpcId: !Ref VpcId
      CidrBlock: !Select 
        - 3
        - !Ref CidrBlocks
      Tags:
        - Key: APPLICATION_NAME
          Value: !Ref ApplicationName
  ClusterSubnet5:
    Condition: 5az
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select 
        - 4
        - !Ref AvailabilityZones
      VpcId: !Ref VpcId
      CidrBlock: !Select 
        - 4
        - !Ref CidrBlocks
      Tags:
        - Key: APPLICATION_NAME
          Value: !Ref ApplicationName
  ClusterSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub 'Allow Client connections to Application: ${ApplicationName}'
      VpcId: !Ref VpcId
      Tags:
        - Key: ApplicationName
          Value: !Ref ApplicationName
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref PortNumber
          ToPort: !Ref PortNumber
          CidrIp: !Ref AccessCidr
      SecurityGroupEgress:
        - IpProtocol: '-1'
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: 0.0.0.0/0
Outputs:
  EndpointAddress:
    Value: !GetAtt 
      - ElastiCacheCluster
      - ConfigurationEndpoint.Address
