- name: Launch ElastiCache Memcached cluster
  cloudformation:
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   stack_name: "apb-memcached-{{ stack_suffix }}"
   state: "present"
   region: "{{ region }}"
   disable_rollback: false
   template: "{{ role_path }}/files/MemCachedCluster.yml"
   role_arn: "{{ aws_cloudformation_role_arn }}"
   template_parameters:
     ApplicationName: "{{ application_name }}"
     VpcId: "{{ VpcId }}"
     NumberOfAvailabilityZones: "{{ NumberOfAvailabilityZones | string }}"
     PreferredMaintenanceWindowDay: "{{ PreferredMaintenanceWindowDay }}"
     PreferredMaintenanceWindowStartTime: "{{ PreferredMaintenanceWindowStartTime }}"
     PreferredMaintenanceWindowEndTime: "{{ PreferredMaintenanceWindowEndTime }}"
     AvailabilityZones: "{{ AvailabilityZones }}"
     CidrBlocks: "{{ CidrBlocks }}"
     AccessCidr: "{{ AccessCidr }}"
     AllowVersionUpgrade: "{{ AllowVersionUpgrade | string }}"
     AZMode: "{{ AZMode }}"
     PortNumber: "{{ PortNumber | string }}"
     EngineVersion: "{{ EngineVersion }}"
     CacheNodeType: "{{ CacheNodeType }}"
     NumCacheNodes: "{{ NumCacheNodes | string }}"
     ClusterType: "{{ ClusterType }}"
   tags:
     Stack: "ansible-cloudformation"
     Application: "ansible-memcached"
     Description: "{{ ansible_user_id }} memcached {{ application_name }}"
  register: elasticache

- name: Check for ElastiCache CloudFormation error logs
  debug:
    var: elasticache.log

- name: Encode bind credentials
  asb_encode_binding:
    fields:
      MEMCACHE_ENDPOINT: "{{ elasticache.stack_outputs.EndpointAddress }}"
      MEMCACHE_PORT: "{{ PortNumber }}"
  when: elasticache.log | length < 1
