- name: Provision ElastiCache
  hosts: localhost
  gather_facts: true
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no

  - role: ansibleplaybookbundle.asb-modules

  - role: provision-memcached-apb-openshift
